### PR TITLE
Follow correct notch path

### PR DESCRIPTION
**Pull request by lscambo13**
This path tries to bring smooth curves around the main display notch.

More detail in here -
https://forum.xda-developers.com/max-pro-m2/themes/elegantnotch-x01bd-magisk-t3945123
https://source.android.com/devices/tech/display/display-cutouts

### CODE REVIEW

**Comment by lscambo13** [comment]
This may require removing any other program/code that tries to hide the notch or filled area.

**Comment by Bauuuuu** [comment]
i am curious about the right side statusbar icons when it gets full. can you show?

**Comment by lscambo13** [comment]
For some reason, my module doesn't have any effect on Arrow which is where I am now.

However, you can look at this photo taken from Havoc. It should look similar on Arrow as well.

https://forum.xda-developers.com/attachment.php?attachmentid=4787670&d=1562338507

**Comment by Bauuuuu** [comment]
i meant the right side notification dot.

**Comment by lscambo13** [comment]
As I mentioned earlier, I'm using Arrow where my module doesn't work (for reasons unknown to me).

If you want to to know about the area that will be left unused, it will still show more icons than our stock rom.

**Pull request closed without merging**
